### ISSUE TITLE
self.releases should not count yanked releases

### ISSUE THREAD

**Issue by kornelski** [rust-alt/cargo-esr#4]
I've yanked all versions of an obsolete crate:

https://crates.io/crates/capi/versions

but it still gets a positive score for having 3 releases.

**Comment by MoSal** [comment]
Handling crates with all-yanked releases fixed in 7de07aa54904f525aa17ebd5886fba0eee89eab2.

After 0de20f5ba55da50abab1a9794b2c790b567e15d1, yanked releases get `+1.5` points, and non-yanked ones get a total `+3.0`.

Note that crate owners shouldn't be discouraged from yanking releases, or be made conscious about
the percentage of yanked releases their crates have.
